//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2_EFKutuphaneCRUDIslemleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemTablo
    {
        public int islemno { get; set; }
        public Nullable<int> ogrno { get; set; }
        public Nullable<int> kitapno { get; set; }
        public Nullable<System.DateTime> atarih { get; set; }
        public Nullable<System.DateTime> vtarih { get; set; }
    
        public virtual kitapTablo kitapTablo { get; set; }
        public virtual OgrenciTablo OgrenciTablo { get; set; }
    }
}
