//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2_EFKutuphaneCRUDIslemleri
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneEntities1 : DbContext
    {
        public KutuphaneEntities1()
            : base("name=KutuphaneEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IslemTablo> IslemTabloes { get; set; }
        public virtual DbSet<kitapTablo> kitapTabloes { get; set; }
        public virtual DbSet<OgrenciTablo> OgrenciTabloes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TurTablo> TurTabloes { get; set; }
        public virtual DbSet<YazarTablo> YazarTabloes { get; set; }
    }
}
