//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2_EFKutuphaneCRUDIslemleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgrenciTablo()
        {
            this.IslemTabloes = new HashSet<IslemTablo>();
        }
    
        public int ogrno { get; set; }
        public string ograd { get; set; }
        public string ogrsoyad { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<System.DateTime> dtarih { get; set; }
        public string sinif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IslemTablo> IslemTabloes { get; set; }
    }
}
